version: "0.2"
logger: "gunicorn.error"
logger_level: 20

builtin_monitor: True

node:
  creation_wait_seconds: 30
  idling_close_minutes: 30
  health_check: true
  health_check_interval: 1
  port: 31942
  creation_kwargs:
    image: "xagentteam/toolserver-node:latest"
    network: "tool-server-network"
    privileged: true
    detach: true
    volumes:
      - "toolserverconfig:/app/assets/config"
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -f -sS 'http://localhost:31942/' > /dev/null || exit 1"]
      interval: 1000000000
      timeout: 3000000000
      retries: 3
      start_period: 0
  device_requests:
  #   - driver: 
  #     count: 1
  #     capabilities:
  #       -
  #         - gpu

  
redirect_to_node_path:
  post:
    - /
    - /execute_tool
    - /get_available_tools
    - /get_json_schema_for_tools
    - /get_json_schema_for_envs
    - /retrieving_tools
    - /register_new_tool
    - /upload_file
    - /download_file
    - /download_workspace
    - /get_workspace_structure
  get:
    - /