version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3001:80"
    depends_on:
      - redis
